### PR TITLE
ssh.js correction to passphrase

### PR DESCRIPTION
**Pull request by apoorv-kulkarni**
- a typo and a last minute if block add on to handle the passphrase exclusively

### CODE REVIEW

**Comment by MCluck90** [comment]
Thanks for catching that. If you remove the `console.log` and correct the indentation, I'd be happy to merge it in.

**Comment by apoorv-kulkarni** [comment]
Yikes, I left it, apologies for that.
I have also corrected the indentation, hope that helps

**Comment by MCluck90** [comment]
Well... The indentation has been fixed in one sense but the indentation across the whole file has been changed. Just look at that file diff, almost every line has been changed now. All those extra whitespace changes hide your useful changes and I want to be able to just glance at what important changes were made in each commit. Sorry to be finicky about it haha.

**Comment by apoorv-kulkarni** [comment]
there you go, no worries :)

**Comment by MCluck90** [comment]
Awesome, thanks! I'll merge it in an push out an update right now.

**Pull request merged**
